### ISSUE TITLE
Questions about the difference between the reproduced results and the experimental results in the paper.

### ISSUE THREAD

**Issue by PeterAlbus** [JiangpengHe/imbalanced_cil#2]
Hi, thanks for open-sourcing this code.
I was interested in the methods mentioned in the paper and tried to reproduce them. But the results of the reproduction differed from what was mentioned in the paper. I clone this code and ran `bash main.sh DGR 0 cifar100 lt 5 20` using pytorch2 and pytorch1 respectively. The experimental results obtained are as follows:
Pytorch 1
TAg Acc
.....
42.2%  17.4%   9.4%  16.2%  22.6%  33.2%  35.6%  22.8%  30.4%  45.6%  22.2%  12.8%  33.0%  36.4%  23.0%  31.8%  33.8%  28.2%  27.4%  41.6% 	Avg.: 28.3% 
Pytorch 2
TAg Acc
.....
 40.8%  18.6%  13.0%  17.2%  23.8%  28.8%  38.2%  21.0%  28.8%  39.0%  25.2%  14.2%  33.6%  32.4%  22.8%  30.6%  35.4%  26.0%  29.0%  38.2% 	Avg.: 27.8% 

This is significantly different from the 34.35% average accuracy in the “CIFAR-100 LT LFS 20 Tasks” scenario mentioned in the paper. What could be the reason for this problem? What is the version of the environment used for the experiment?

**Comment by JiangpengHe** [comment]
For the experiments, we use python 3.9.4 and torch 2.0.1. 
Your shared results look like the **final step accuracy** instead of the **average accuracy**. The average accuracy is calculated by averaging the accuracy after learning each task, and your 27.8% is only the accuracy after learning the last task. Basically, look for TAg Acc table and calculate the mean of all the Avg accuracies (there should be 20 if you have 20 tasks). Let me know if there are other questions.

**Comment by PeterAlbus** [comment]
Thank you for your answer, I was mistaken!
